### ISSUE TITLE
Could we update the corpus with the Oss-Fuzz corpus?

### ISSUE THREAD

**Issue by Phasip** [curl/curl-fuzzer#34]
Hello! 

The corpora/ folder seems old, I figure that OSS-Fuzz has generated a better corpus by now.

Would it make sense to update this repo with the latest corpus?
If not, could I get a copy of the corpus by other means? ( According to https://google.github.io/oss-fuzz/advanced-topics/corpora/ I can't access the corpus of Oss-Fuzz =( )

**Comment by bagder** [comment]
Seems fair. @cmeister2, do you have the tools around already to be able to do this? gsutil and what not.

**Comment by cmeister2** [comment]
I'm working on getting these! Just have to have some spare time...
