### ISSUE TITLE
ossfuzz.sh is under the Apache 2 license, while the rest of the code is MIT

### ISSUE THREAD

**Issue by aiuto** [curl/curl-fuzzer#49]
https://github.com/curl/curl-fuzzer/blob/master/ossfuzz.sh
- has headers saying Apache 2.0 and copyright by Google.
- the LICENSE file only says MIT

@cmeister2  Is that intentional, or accidental?  I know the name 'ossfuzz.sh' is reused in other projects, but the pattern I am seeing is that each project writes their own script (as did you for curl_fuzzer), so the attribution is to the project.

**Comment by bagder** [comment]
I'm totally fine with that, yes. Looking at the history of the file, you added it and it certainly looks like your original work and no other contributors, and then you're entitled to change the license just fine.
