### ISSUE TITLE
Up-to-date corpus from OSS-Fuzz

### ISSUE THREAD

**Issue by z2-2z** [curl/curl-fuzzer#56]
Would it be possible to merge the current corpus from OSS-fuzz into this repository?

The last time this was requested was over two years ago in #34 and it would be nice
to reflect the newest versions.

**Comment by z2-2z** [comment]
In the docs it says
> To get access to a project's corpora, you must be listed as the primary contact or as an auto cc in the project's project.yaml file

**Comment by cmeister2** [comment]
Looks like all the (public) corpuses are available at
https://storage.googleapis.com/curl-backup.clusterfuzz-external.appspot.com/corpus/libFuzzer/curl_fuzzer_http/public.zip
<replace
curl_fuzzer_http for whichever fuzzer you want to run>. Least, this is what
the CI uses to run.
